services:
  demo_codexsun_com:
    image: cloudxis:v2
    container_name: demo_codexsun_com
    ports:
      - "8005:8000"
      - "5005:5005"
      - "3005:3005"
    volumes:
      - ../../../../cloud/demo_codexsun_com:/home/devops/cloud
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true